[workspace]
members = ["crates/*"]
resolver = "1"

[workspace.package]
edition = "2021"
rust-version = "1.80"
license = "MIT"
version = "0.0.1"

[workspace.dependencies]
chrome_cookie = { path = "crates/chrome_cookie", version = "0.0.1" }
