package = "zfh"
version = "0.0.3"
lua = ">= 5.1"

[description]
summary = "A library to convert many markup languages to Zhihu flavored HTML."
detailed = ""
maintainer = "Wu"
labels = ["neovim"]
homepage = "https://github.com/pxwg/zhihu.nvim/tree/main/packages/zfh"
license = 'MIT'

[source]
url = "https://github.com/pxwg/zhihu.nvim/archive/$(VERSION).zip"
dir = "zhihu.nvim-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
htmlparser = " >= 0.0.1"
html-entities = " >= 0.0.1"
luasocket = " >= 0.0.1"
vim = " >= 0.0.1"

[test]
type = "busted"

[deploy]
wrap_bin_scripts = false

[build]
type = "rust-mlua"

[build.modules]
markdown_to_html = "markdown_to_html"

[build.install.lua]
"zfh.generator" = "lua/zfh/generator.lua"
"zfh.generator.markdown" = "lua/zfh/generator/markdown.lua"
"zfh.translator" = "lua/zfh/translator.lua"
"zfh.translator.cmd" = "lua/zfh/translator/cmd.lua"
"zfh" = "lua/zfh.lua"

[build.install.bin]
zfh = "bin/zfh"
