package = "zfh"
version = "0.0.1"
lua = ">= 5.1"

[description]
summary = "A library to convert many markup languages to Zhihu flavored HTML."
detailed = ""
maintainer = "Wu"
labels = ["neovim"]
homepage = "https://github.com/pxwg/zhihu.nvim/tree/main/packages/zfh"
license = 'MIT'

[source]
url = "https://github.com/pxwg/zhihu.nvim/archive/$(VERSION).zip"
dir = "zhihu.nvim-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
htmlparser = " >= 0.0.1"
html-entities = " >= 0.0.1"
vim = " >= 0.0.1"

[test]
type = "busted"

[build]
type = "rust-mlua"

[build.modules]
markdown_to_html = "markdown_to_html"

[build.install.lua]
"zfh.markdown" = "lua/zfh/markdown.lua"
"zfh" = "lua/zfh.lua"
